### ISSUE TITLE
View GRPC Server: Enforce Signature Verification

### ISSUE THREAD

**Issue by adecaro** [hyperledger-labs/fabric-smart-client#27]
The GRPC Server should enforce that any command is signed by:

- [x] The identity of the FSC node
- [x] Any administrator of the FSC node. Administrators will be defined in a specific section of the configuration file:
```yaml
fsc:
  admin:
    certs:
    - admin1.pem
    - admin1.pem
```
