### ISSUE TITLE
Retrieve public MSP information from channel config for fabric driver resolvers

### ISSUE THREAD

**Issue by davidkel** [hyperledger-labs/fabric-smart-client#413]
For the fabric driver resolvers you might have an entry such as 
```
    endpoint:
      resolvers: 
      - name: approver
        domain: org1.example.com
        identity:
          mspID: Org1MSP
          path: /home/dave/github-cloned/fabric-smart-client/samples/fabric/iou/testdata/fabric.default/crypto/peerOrganizations/org1.example.com/users/approver@org1.example.com/msp/signcerts/approver@org1.example.com-cert.pem
 ```

Currenly the path either refers to the the public cert of the signer or the nodes public msp (ie without any private keys). Access to the public MSP is required in case the signer certificate is sanitized by fabric and thus doesn't match the certificate stored in the MSP file system.

It would be better to obtain the public MSP from the channel configuration instead
