### ISSUE TITLE
typos in opentelemetry configuration

### ISSUE THREAD

**Issue by arner** [hyperledger-labs/fabric-smart-client#643]
The protocol for opentelemetry is called [OTLP](https://opentelemetry.io/docs/specs/otlp/).

In core.yaml and the FSC codebase, it's called both `optl` and `otpl`. To the point where you have to:

```yaml
tracing:
    provider: otpl
    optl:
      ...
```

This is quite confusing 😅.

Propose to change them to `opentelemetry` in core.yaml, and otlp where we want a shorthand in the code.
